[package]
name = "arch-audit"
version = "0.1.0"
authors = ["Andrea Scarpino <me@andreascarpino.it>"]
description = "An utility like pkg-audit for Arch Linux based on Arch CVE Monitoring Team data"
repository = "https://github.com/ilpianista/arch-audit"
license = "MIT"
readme = "README.md"
keywords = ["archlinux", "security"]

[[bin]]
name = "arch-audit"

[dependencies]
alpm = "^0.2"
curl = "*"
env_logger = "^0.3"
json = "*"
log = "*"
select = "^0.3"
