[package]
name = "arch-audit"
version = "0.1.7"
authors = ["Andrea Scarpino <me@andreascarpino.it>"]
description = "An utility like pkg-audit for Arch Linux based on Arch CVE Monitoring Team data"
repository = "https://github.com/ilpianista/arch-audit"
license = "MIT"
readme = "README.md"
keywords = ["archlinux", "security"]

[[bin]]
name = "arch-audit"

[dependencies]
alpm = "^0.4"
clap = {version = "^2", features = ["yaml"]}
curl = "^0.4"
env_logger = "^0.3"
itertools = "^0.5"
log = "^0.3"
rustc-serialize = "^0.3"
